export const LOGGER = {
  INFO: 'info',
  ERROR: 'error',
};

export const HTTP_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  VALIDATION_ERROR: 422,
  INTERNAL_SERVER_ERROR: 500,
};

export const RESPONSE_SUCCESS = {
  TRUE: true,
  FALSE: false,
};

export const MESSAGES = {
  REQUEST_CREATE_API_START: 'REQUEST_CREATE_API_START | ',
  REQUEST_CREATE_API_SUCCESS: 'REQUEST_CREATE_API_SUCCESS | ',
  REQUEST_CREATE_API_FAILED: 'REQUEST_CREATE_API_FAILED | ',
};
