export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const RETURN_STATE = "RETURN_STATE";

export const LOGOUT_USER_LISTEN = "Login/LOGOUT_USER_LISTEN"
export const LOGOUT_USER_SUCCESS = "Login/LOGOUT_USER_SUCCESS"

export const GET_USER = "LOGIN/GET_USER";
export const GET_USER_SUCCESS = "LOGIN/GET_USER_SUCCESS";
export const GET_USER_ERROR = "LOGIN/GET_USER_ERROR";
